
    import { Music, FileText, Film, FileImage as ImageIcon, BookOpen, HardDrive, Globe, Cpu, Archive, Hash } from 'lucide-react';

    export const allToolsData = {
      audio: {
        name: 'Audio Converters',
        icon: Music,
        color: 'bg-rose-500',
        tools: [
          { id: 'to-aac', name: 'Convert to AAC', description: 'Convert audio to Advanced Audio Coding format.' },
          { id: 'to-aiff', name: 'Convert to AIFF', description: 'Convert audio to Audio Interchange File Format.' },
          { id: 'to-flac', name: 'Convert to FLAC', description: 'Convert audio to Free Lossless Audio Codec.' },
          { id: 'to-m4a', name: 'Convert to M4A', description: 'Convert audio to MPEG-4 Audio Layer.' },
          { id: 'to-m4r', name: 'Convert to M4R', description: 'Convert audio to iPhone Ringtone format.' },
          { id: 'to-mmf', name: 'Convert to MMF', description: 'Convert audio to Synthetic Music Mobile Application Format.' },
          { id: 'to-mp3', name: 'Convert to MP3', description: 'Convert audio to MPEG Audio Layer-3.' },
          { id: 'to-ogg', name: 'Convert to OGG', description: 'Convert audio to Ogg Vorbis format.' },
          { id: 'to-opus', name: 'Convert to OPUS', description: 'Convert audio to Opus audio codec.' },
          { id: 'to-wav', name: 'Convert to WAV', description: 'Convert audio to Waveform Audio File Format.' },
          { id: 'to-wma', name: 'Convert to WMA', description: 'Convert audio to Windows Media Audio.' },
        ],
      },
      documents: {
        name: 'Document Converters',
        icon: FileText,
        color: 'bg-blue-500',
        tools: [
          { id: 'to-doc', name: 'Convert to DOC', description: 'Convert documents to Microsoft Word Document (legacy).' },
          { id: 'to-docx', name: 'Convert to DOCX', description: 'Convert documents to Microsoft Word Document.' },
          { id: 'to-html', name: 'Convert to HTML', description: 'Convert documents to HyperText Markup Language.' },
          { id: 'to-odt', name: 'Convert to ODT', description: 'Convert documents to OpenDocument Text.' },
          { id: 'to-pdf', name: 'Convert to PDF', description: 'Convert documents to Portable Document Format.' },
          { id: 'to-ppt', name: 'Convert to PPT', description: 'Convert documents to Microsoft PowerPoint Presentation (legacy).' },
          { id: 'to-pptx', name: 'Convert to PPTX', description: 'Convert documents to Microsoft PowerPoint Presentation.' },
          { id: 'to-rtf', name: 'Convert to RTF', description: 'Convert documents to Rich Text Format.' },
          { id: 'to-txt', name: 'Convert to TXT', description: 'Convert documents to Plain Text.' },
          { id: 'to-xlsx', name: 'Convert to XLSX', description: 'Convert documents to Microsoft Excel Spreadsheet.' },
        ],
      },
      web: {
        name: 'Web Service Converters',
        icon: Globe,
        color: 'bg-indigo-500',
        tools: [
          { id: 'for-facebook', name: 'Convert for Facebook', description: 'Optimize media for Facebook.' },
          { id: 'for-instagram', name: 'Convert for Instagram', description: 'Optimize media for Instagram.' },
          { id: 'for-telegram', name: 'Convert for Telegram', description: 'Optimize media for Telegram.' },
          { id: 'for-twitter', name: 'Convert for Twitter', description: 'Optimize media for Twitter.' },
          { id: 'for-whatsapp', name: 'Convert for WhatsApp', description: 'Optimize media for WhatsApp.' },
          { id: 'for-dailymotion', name: 'Convert for Dailymotion', description: 'Optimize media for Dailymotion.' },
          { id: 'for-twitch', name: 'Convert for Twitch', description: 'Optimize media for Twitch.' },
          { id: 'for-viber', name: 'Convert for Viber', description: 'Optimize media for Viber.' },
          { id: 'for-vimeo', name: 'Convert for Vimeo', description: 'Optimize media for Vimeo.' },
          { id: 'for-youtube', name: 'Convert for YouTube', description: 'Optimize media for YouTube.' },
          { id: 'for-tiktok', name: 'Convert for TikTok', description: 'Optimize media for TikTok.' },
        ],
      },
      software: {
        name: 'Software Converters',
        icon: Cpu,
        color: 'bg-slate-500',
        tools: [
          { id: 'excel-converter', name: 'Excel Converter', description: 'Convert Excel files to other formats.' },
          { id: 'powerpoint-converter', name: 'PowerPoint Converter', description: 'Convert PowerPoint files to other formats.' },
          { id: 'word-converter', name: 'Word Converter', description: 'Convert Word files to other formats.' },
        ],
      },
      video: {
        name: 'Video Converters',
        icon: Film,
        color: 'bg-purple-500',
        tools: [
          { id: 'to-3g2', name: 'Convert to 3G2', description: 'Convert video to 3GPP2 format.' },
          { id: 'to-3gp', name: 'Convert to 3GP', description: 'Convert video to 3GPP format.' },
          { id: 'to-avi', name: 'Convert to AVI', description: 'Convert video to Audio Video Interleave.' },
          { id: 'to-flv', name: 'Convert to FLV', description: 'Convert video to Flash Video.' },
          { id: 'to-mkv', name: 'Convert to MKV', description: 'Convert video to Matroska Video.' },
          { id: 'to-mov', name: 'Convert to MOV', description: 'Convert video to Apple QuickTime Movie.' },
          { id: 'to-mp4', name: 'Convert to MP4', description: 'Convert video to MPEG-4 Part 14.' },
          { id: 'to-mpg', name: 'Convert to MPG', description: 'Convert video to MPEG.' },
          { id: 'to-ogv', name: 'Convert to OGV', description: 'Convert video to Ogg Video.' },
          { id: 'to-webm', name: 'Convert to WEBM', description: 'Convert video to WebM format.' },
        ],
      },
      ebook: {
        name: 'Ebook Converters',
        icon: BookOpen,
        color: 'bg-teal-500',
        tools: [
          { id: 'to-azw', name: 'Convert to AZW', description: 'Convert ebooks to Amazon Kindle format.' },
          { id: 'to-epub', name: 'Convert to ePub', description: 'Convert ebooks to Electronic Publication format.' },
          { id: 'to-fb2', name: 'Convert to FB2', description: 'Convert ebooks to FictionBook 2.0.' },
          { id: 'to-lit', name: 'Convert to LIT', description: 'Convert ebooks to Microsoft Reader format.' },
          { id: 'to-lrf', name: 'Convert to LRF', description: 'Convert ebooks to Sony Portable Reader Format.' },
          { id: 'to-mobi', name: 'Convert to MOBI', description: 'Convert ebooks to Mobipocket E-book format.' },
          { id: 'to-pdb', name: 'Convert to PDB', description: 'Convert ebooks to Palm DataBase format.' },
          { id: 'to-pdf-ebook', name: 'Convert to PDF (Ebook)', description: 'Convert ebooks to Portable Document Format.' },
          { id: 'to-tcr', name: 'Convert to TCR', description: 'Convert ebooks to Psion Series 3 Text Cratridge Reader format.' },
        ],
      },
      drive: {
        name: 'Drive Converters',
        icon: HardDrive,
        color: 'bg-lime-500',
        tools: [
          { id: 'for-android', name: 'Convert for Android', description: 'Optimize media for Android devices.' },
          { id: 'for-blackberry', name: 'Convert for Blackberry', description: 'Optimize media for Blackberry devices.' },
          { id: 'for-xbox', name: 'Convert for XBOX', description: 'Optimize media for XBOX consoles.' },
          { id: 'for-ipad', name: 'Convert for iPad', description: 'Optimize media for iPad devices.' },
          { id: 'for-iphone', name: 'Convert for iPhone', description: 'Optimize media for iPhone devices.' },
          { id: 'for-ipod', name: 'Convert for iPod', description: 'Optimize media for iPod devices.' },
          { id: 'for-nintendo-3ds', name: 'Convert for Nintendo 3DS', description: 'Optimize media for Nintendo 3DS.' },
          { id: 'for-nintendo-ds', name: 'Convert for Nintendo DS', description: 'Optimize media for Nintendo DS.' },
          { id: 'for-playstation', name: 'Convert for PlayStation', description: 'Optimize media for PlayStation consoles.' },
          { id: 'for-psp', name: 'Convert for PSP', description: 'Optimize media for PlayStation Portable.' },
          { id: 'for-wii', name: 'Convert for Wii', description: 'Optimize media for Nintendo Wii.' },
        ],
      },
      images: {
        name: 'Image Converters',
        icon: ImageIcon,
        color: 'bg-amber-500',
        tools: [
          { id: 'to-bmp', name: 'Convert to BMP', description: 'Convert images to Bitmap Image File.' },
          { id: 'to-eps', name: 'Convert to EPS', description: 'Convert images to Encapsulated PostScript.' },
          { id: 'to-hdr-exr', name: 'Convert to HDR/EXR', description: 'Convert images to High Dynamic Range/Extended Dynamic Range.' },
          { id: 'to-gif', name: 'Convert to GIF', description: 'Convert images to Graphics Interchange Format.' },
          { id: 'to-ico', name: 'Convert to ICO', description: 'Convert images to Icon file format.' },
          { id: 'to-jpg', name: 'Convert to JPG', description: 'Convert images to Joint Photographic Experts Group format.' },
          { id: 'to-png', name: 'Convert to PNG', description: 'Convert images to Portable Network Graphics.' },
          { id: 'to-svg', name: 'Convert to SVG', description: 'Convert images to Scalable Vector Graphics.' },
          { id: 'to-tga', name: 'Convert to TGA', description: 'Convert images to Truevision TGA.' },
          { id: 'to-tiff', name: 'Convert to TIFF', description: 'Convert images to Tagged Image File Format.' },
          { id: 'to-wbmp', name: 'Convert to WBMP', description: 'Convert images to Wireless Application Protocol Bitmap Format.' },
          { id: 'to-webp', name: 'Convert to WebP', description: 'Convert images to WebP format.' },
        ],
      },
      archive: {
        name: 'Archive Converters',
        icon: Archive,
        color: 'bg-cyan-500',
        tools: [
          { id: 'to-7z', name: 'Convert to 7Z', description: 'Create 7Z archives.' },
          { id: 'to-tar-bz2', name: 'Convert to TAR.BZ2', description: 'Create TAR.BZ2 archives.' },
          { id: 'to-tar-gz', name: 'Convert to TAR.GZ', description: 'Create TAR.GZ archives.' },
          { id: 'to-zip', name: 'Convert to ZIP', description: 'Create ZIP archives.' },
        ],
      },
      hash: {
        name: 'Hash Generators',
        icon: Hash,
        color: 'bg-pink-500',
        tools: [
          { id: 'gen-ripemd-128', name: 'RIPEMD-128', description: 'Generate RIPEMD-128 hash.' },
          { id: 'gen-ripemd-160', name: 'RIPEMD-160', description: 'Generate RIPEMD-160 hash.' },
          { id: 'gen-sha-1', name: 'SHA-1', description: 'Generate SHA-1 hash.' },
          { id: 'gen-sha-256', name: 'SHA-256', description: 'Generate SHA-256 hash.' },
          { id: 'gen-sha-384', name: 'SHA-384', description: 'Generate SHA-384 hash.' },
          { id: 'gen-sha-512', name: 'SHA-512', description: 'Generate SHA-512 hash.' },
          { id: 'gen-snefru', name: 'Snefru', description: 'Generate Snefru hash.' },
          { id: 'gen-tiger-128', name: 'Tiger-128', description: 'Generate Tiger-128 hash.' },
          { id: 'gen-tiger-160', name: 'Tiger-160', description: 'Generate Tiger-160 hash.' },
          { id: 'gen-tiger-192', name: 'Tiger-192', description: 'Generate Tiger-192 hash.' },
          { id: 'gen-whirlpool', name: 'Whirlpool', description: 'Generate Whirlpool hash.' },
          { id: 'gen-adler32', name: 'Adler32', description: 'Generate Adler32 checksum.' },
          { id: 'gen-htpasswd', name: 'htpasswd Apache', description: 'Generate htpasswd for Apache.' },
          { id: 'gen-blowfish', name: 'Blowfish', description: 'Generate Blowfish hash/cipher.' },
          { id: 'gen-crc-32', name: 'CRC-32', description: 'Generate CRC-32 checksum.' },
          { id: 'gen-crc-32b', name: 'CRC-32B', description: 'Generate CRC-32B checksum.' },
          { id: 'gen-des', name: 'DES', description: 'Generate DES hash/cipher.' },
          { id: 'gen-gost', name: 'Gost', description: 'Generate Gost hash.' },
          { id: 'gen-haval-128', name: 'Haval-128', description: 'Generate Haval-128 hash.' },
          { id: 'gen-md4', name: 'MD4', description: 'Generate MD4 hash.' },
          { id: 'gen-md5', name: 'MD5', description: 'Generate MD5 hash.' },
        ],
      },
    };
  