export const mainNavLinks = [
  { to: "/", text: "Home", icon: "Home" },
  { to: "/tools", text: "All Tools", icon: "LayoutGrid" },
  { to: "/features", text: "Features", icon: "Sparkles" },
  { to: "/about", text: "About", icon: "Info" },
  { to: "/blog", text: "Blog", icon: "Rss" },
  { to: "/terms", text: "Terms", icon: "FileText" },
  { to: "/disclaimer", text: "Disclaimer", icon: "AlertTriangle" },
];

export const allToolCategories = [
  { name: "Image Tools", path: "/image-tools", icon: "Image", color: "text-green-500 dark:text-green-400", description: "Convert, compress, resize images and more." },
  { name: "Video Tools", path: "/video-tools", icon: "Video", color: "text-blue-500 dark:text-blue-400", description: "Convert videos, create GIFs, mute, trim." },
  { name: "MP3 Tools", path: "/mp3-tools", icon: "Music2", color: "text-emerald-500 dark:text-emerald-400", description: "Play, analyze, and convert MP3 files client-side." },
  { name: "Document Tools", path: "/document-tools", icon: "FileText", color: "text-indigo-600 dark:text-indigo-400", description: "Convert PDF, Word, Excel, PowerPoint." },
  { name: "Text Tools", path: "/text-tools", icon: "Type", color: "text-slate-500 dark:text-slate-400", description: "Count words, change case, generate text." },
  { name: "QR/Barcode Tools", path: "/qr-barcode-tools", icon: "QrCode", color: "text-neutral-600 dark:text-neutral-400", description: "Generate and scan QR codes and barcodes." },
  { name: "Unit Converters", path: "/unit-converters", icon: "SlidersHorizontal", color: "text-amber-500 dark:text-amber-400", description: "Convert length, weight, temperature, etc." },
  { name: "Math Tools", path: "/math-tools", icon: "Calculator", color: "text-orange-500 dark:text-orange-400", description: "Calculators for percentage, age, BMI, etc." },
  { name: "Color Tools", path: "/color-tools", icon: "Palette", color: "text-rose-500 dark:text-rose-400", description: "Pick colors, generate palettes, check contrast." },
  { name: "Developer Tools", path: "/developer-tools", icon: "Code2", color: "text-cyan-500 dark:text-cyan-400", description: "Format JSON, Base64, HTML, CSS, JS & more." },
  { name: "Security Tools", path: "/security-tools", icon: "ShieldCheck", color: "text-lime-500 dark:text-lime-400", description: "Generate passwords, hashes, encrypt text & more." },
  { name: "Miscellaneous Tools", path: "/miscellaneous-tools", icon: "Sparkles", color: "text-violet-500 dark:text-violet-400", description: "Fun and handy utilities for everyday tasks." },
  { name: "Science Tools", path: "/science-tools", icon: "FlaskConical", color: "text-sky-500 dark:text-sky-400", description: "Explore science with calculators and explorers." },
  { name: "Marketing Tools", path: "/marketing-tools", icon: "Megaphone", color: "text-red-500 dark:text-red-400", description: "Boost campaigns with SEO, email, and content tools." },
  { name: "Social Media Tools", path: "/social-media-tools", icon: "Share2", color: "text-fuchsia-500 dark:text-fuchsia-400", description: "Boost your social presence with specialized tools." },
  { name: "File Tools", path: "/file-tools", icon: "FolderKanban", color: "text-purple-500 dark:text-purple-400", description: "Compress, merge, split, convert, and manage files in-browser." },
  { name: "Health & Fitness Tools", path: "/health-fitness-tools", icon: "HeartPulse", color: "text-teal-500 dark:text-teal-400", description: "Monitor, calculate, and improve your health & fitness." },
  { name: "Calendar & Time Tools", path: "/calendar-time-tools", icon: "CalendarClock", color: "text-yellow-500 dark:text-yellow-400", description: "Manage dates, times, and calendars effectively." },
  { name: "Finance Tools", path: "/finance-tools", icon: "Landmark", color: "text-stone-500 dark:text-stone-400", description: "Calculators for loans, investments, taxes, and savings." },
  { name: "Geography Tools", path: "/geography-tools", icon: "Globe2", color: "text-blue-600 dark:text-blue-400", description: "Explore the world with location, time, and distance tools." },
  { name: "AI Tools", path: "/ai-tools", icon: "BrainCircuit", color: "text-pink-500 dark:text-pink-400", description: "Smart utilities for text analysis, content generation, and more." },
  { name: "Language Tools", path: "/language-tools", icon: "Languages", color: "text-orange-600 dark:text-orange-400", description: "Translate, detect, and convert text between languages." },
  { name: "Game Tools", path: "/game-tools", icon: "Gamepad2", color: "text-red-600 dark:text-red-400", description: "Fun utilities and tools for gaming." },
  { name: "System Tools", path: "/system-tools", icon: "HardDrive", color: "text-gray-600 dark:text-gray-400", description: "Check your device's status and network info." },
];

export const individualTools = [
  { name: "JPG to PNG", path: "/jpg-to-png", category: "Image Tools", description: "Convert JPG images to PNG format." },
  { name: "PNG to JPG", path: "/png-to-jpg", category: "Image Tools", description: "Convert PNG images to JPG format." },
  { name: "Image Compressor", path: "/image-compressor", category: "Image Tools", description: "Compress images to reduce file size." },
  { name: "Image Resizer", path: "/image-resizer", category: "Image Tools", description: "Resize images to specific dimensions." },
  { name: "Image Cropper", path: "/image-cropper", category: "Image Tools", description: "Crop images to a selected area." },
  { name: "Image Rotator", path: "/image-rotator", category: "Image Tools", description: "Rotate images by specified degrees." },
  { name: "Image Flipper", path: "/image-flipper", category: "Image Tools", description: "Flip images horizontally or vertically." },
  { name: "Image to Grayscale", path: "/image-grayscale", category: "Image Tools", description: "Convert images to grayscale." },
  { name: "Image Blur", path: "/image-blur", category: "Image Tools", description: "Apply blur effect to images." },
  { name: "Image Pixelator", path: "/image-pixelator", category: "Image Tools", description: "Pixelate images for an artistic effect." },
  { name: "Image Brightness", path: "/image-brightness", category: "Image Tools", description: "Adjust the brightness of images." },
  { name: "Image to Base64", path: "/image-to-base64", category: "Image Tools", description: "Convert images to Base64 strings." },

  { name: "Video to GIF", path: "/video-to-gif", category: "Video Tools", description: "Convert video clips to animated GIFs." },
  { name: "Mute Video", path: "/mute-video", category: "Video Tools", description: "Remove audio from video files." },
  { name: "Video Trimmer", path: "/video-trimmer", category: "Video Tools", description: "Trim video clips to a specific duration." },

  { name: "MP3 Metadata Viewer", path: "/mp3-metadata-viewer", category: "MP3 Tools", description: "View ID3 tags and metadata of your MP3 files." },
  { name: "MP3 to Base64 Converter", path: "/mp3-base64-converter", category: "MP3 Tools", description: "Convert MP3 files to Base64 strings and vice-versa." },
  { name: "MP3 File Renamer", path: "/mp3-renamer", category: "MP3 Tools", description: "Rename MP3 files and download with the new name." },
  { name: "Upload MP3", path: "/mp3-file-helper", category: "MP3 Tools", description: "Upload and download MP3 files." },
  { name: "MP3 Loop Player", path: "/mp3-loop-player", category: "MP3 Tools", description: "Loop sections of your MP3 files." },
  { name: "MP3 Info Viewer", path: "/mp3-info-viewer", category: "MP3 Tools", description: "View basic info like duration and size of an MP3." },
  
  { name: "Word to PDF", path: "/word-to-pdf", category: "Document Tools", description: "Convert Word documents to PDF." },
  { name: "PDF to Word", path: "/pdf-to-word", category: "Document Tools", description: "Convert PDF files to Word documents." },
  { name: "PDF to Image", path: "/pdf-to-image", category: "Document Tools", description: "Convert PDF pages to images." },
  { name: "Image to PDF", path: "/image-to-pdf", category: "Document Tools", description: "Convert images to PDF files." },
  { name: "Excel to PDF", path: "/excel-to-pdf", category: "Document Tools", description: "Convert Excel spreadsheets to PDF." },
  { name: "PowerPoint to PDF", path: "/powerpoint-to-pdf", category: "Document Tools", description: "Convert PowerPoint presentations to PDF." },
  { name: "Text to PDF", path: "/text-to-pdf", category: "Document Tools", description: "Convert plain text to PDF." },
  { name: "PDF to Text", path: "/pdf-to-text", category: "Document Tools", description: "Extract text content from PDF files." },
  { name: "Merge PDFs", path: "/merge-pdfs", category: "Document Tools", description: "Combine multiple PDF files into one." },
  { name: "Split PDF", path: "/split-pdf", category: "Document Tools", description: "Split a PDF file into multiple parts." },
  { name: "Protect PDF", path: "/protect-pdf", category: "Document Tools", description: "Add password protection to PDF files." },
  { name: "Unlock PDF", path: "/unlock-pdf", category: "Document Tools", description: "Remove password from PDF files." },
  { name: "HTML to PDF", path: "/html-to-pdf", category: "Document Tools", description: "Convert HTML content or files to PDF." },
  { name: "PDF Page Editor", path: "/pdf-editor", category: "Document Tools", description: "Reorder or delete pages from your PDF documents." },
  { name: "Rotate PDF Pages", path: "/rotate-pdf", category: "Document Tools", description: "Rotate selected pages within a PDF document." },

  { name: "Word Counter", path: "/word-counter", category: "Text Tools", description: "Count words in a text." },
  { name: "Character Counter (Old)", path: "/character-counter", category: "Text Tools", description: "Count characters in a text (old)." },
  { name: "Sentence Counter", path: "/sentence-counter", category: "Text Tools", description: "Count sentences in a text." },
  { name: "Paragraph Counter", path: "/paragraph-counter", category: "Text Tools", description: "Count paragraphs in a text." },
  { name: "Remove Duplicate Lines", path: "/remove-duplicate-lines", category: "Text Tools", description: "Remove duplicate lines from text." },
  { name: "Remove Line Breaks", path: "/remove-line-breaks", category: "Text Tools", description: "Remove line breaks from text." },
  { name: "Text to Uppercase", path: "/text-to-uppercase", category: "Text Tools", description: "Convert text to uppercase." },
  { name: "Text to Lowercase", path: "/text-to-lowercase", category: "Text Tools", description: "Convert text to lowercase." },
  { name: "Title Case Converter", path: "/title-case-converter", category: "Text Tools", description: "Convert text to title case." },
  { name: "Reverse Text", path: "/reverse-text", category: "Text Tools", description: "Reverse the order of characters in text." },
  { name: "Text to Binary", path: "/text-to-binary", category: "Text Tools", description: "Convert text to binary code." },
  { name: "Binary to Text", path: "/binary-to-text", category: "Text Tools", description: "Convert binary code to text." },
  { name: "Text to Speech", path: "/text-to-speech", category: "Text Tools", description: "Convert text into spoken audio." },
  { name: "Find and Replace", path: "/find-and-replace", category: "Text Tools", description: "Find and replace text within a document." },
  { name: "Online Notepad", path: "/online-notepad", category: "Text Tools", description: "A simple online notepad." },
  { name: "Remove Extra Spaces", path: "/remove-extra-spaces", category: "Text Tools", description: "Remove redundant spaces from text." },
  { name: "Word Occurrence Counter", path: "/word-occurrence-counter", category: "Text Tools", description: "Count occurrences of a specific word." },
  { name: "Word Frequency Analyzer", path: "/word-frequency-analyzer", category: "Text Tools", description: "Analyze the frequency of words in text." },
  { name: "Remove Empty Lines", path: "/remove-empty-lines", category: "Text Tools", description: "Remove empty lines from text." },
  { name: "Text Encrypt/Decrypt (Old)", path: "/text-encrypt-decrypt", category: "Text Tools", description: "Encrypt or decrypt text (old)." },

  { name: "QR Code Generator", path: "/qr-code-generator", category: "QR/Barcode Tools", description: "Generate QR codes." },
  { name: "QR Code Scanner", path: "/qr-code-scanner", category: "QR/Barcode Tools", description: "Scan QR codes using your camera." },
  { name: "Barcode Generator", path: "/barcode-generator", category: "QR/Barcode Tools", description: "Generate various types of barcodes." },
  { name: "Barcode Scanner", path: "/barcode-scanner", category: "QR/Barcode Tools", description: "Scan barcodes using your camera or an image." },
  { name: "WiFi QR Generator", path: "/wifi-qr-generator", category: "QR/Barcode Tools", description: "Generate QR codes for WiFi access." },
  { name: "vCard QR Generator", path: "/vcard-qr-generator", category: "QR/Barcode Tools", description: "Generate QR codes for contact cards." },
  { name: "QR Image Decoder", path: "/qr-image-decoder", category: "QR/Barcode Tools", description: "Decode QR codes from uploaded images." },

  { name: "Length Converter", path: "/length-converter", category: "Unit Converters", description: "Convert units of length." },
  { name: "Weight Converter", path: "/weight-converter", category: "Unit Converters", description: "Convert units of weight." },
  { name: "Temperature Converter", path: "/temperature-converter", category: "Unit Converters", description: "Convert units of temperature." },
  { name: "Speed Converter", path: "/speed-converter", category: "Unit Converters", description: "Convert units of speed." },
  { name: "Area Converter", path: "/area-converter", category: "Unit Converters", description: "Convert units of area." },
  { name: "Volume Converter", path: "/volume-converter", category: "Unit Converters", description: "Convert units of volume." },
  { name: "Time Converter", path: "/time-converter", category: "Unit Converters", description: "Convert units of time." },
  { name: "Pressure Converter", path: "/pressure-converter", category: "Unit Converters", description: "Convert units of pressure." },
  { name: "Energy Converter", path: "/energy-converter", category: "Unit Converters", description: "Convert units of energy." },
  { name: "Data Converter", path: "/data-converter", category: "Unit Converters", description: "Convert units of digital data." },

  { name: "Percentage Calculator", path: "/percentage-calculator", category: "Math Tools", description: "Calculate percentages." },
  { name: "Scientific Calculator", path: "/scientific-calculator", category: "Math Tools", description: "Perform scientific calculations." },
  { name: "Average Calculator", path: "/average-calculator", category: "Math Tools", description: "Calculate mean, median, and mode." },
  { name: "Age Calculator (Math)", path: "/age-calculator", category: "Math Tools", description: "Calculate age from a birth date." },
  { name: "Simple Interest Calculator", path: "/simple-interest-calculator", category: "Math Tools", description: "Calculate simple interest." },
  { name: "Compound Interest Calculator", path: "/compound-interest-calculator", category: "Math Tools", description: "Calculate compound interest." },
  { name: "BMI Calculator (Math)", path: "/bmi-calculator", category: "Math Tools", description: "Calculate Body Mass Index." },
  { name: "Fraction to Decimal", path: "/fraction-to-decimal", category: "Math Tools", description: "Convert fractions to decimals." },
  { name: "Number to Words", path: "/number-to-words", category: "Math Tools", description: "Convert numbers to words." },
  { name: "LCM & HCF Calculator", path: "/lcm-hcf-calculator", category: "Math Tools", description: "Calculate LCM and HCF." },
  { name: "Factorial Calculator", path: "/factorial-calculator", category: "Math Tools", description: "Calculate factorials." },

  { name: "Color Picker", path: "/color-picker", category: "Color Tools", description: "Pick colors and get HEX/RGB/HSL codes." },
  { name: "HEX to RGB Converter", path: "/hex-to-rgb-converter", category: "Color Tools", description: "Convert HEX color codes to RGB." },
  { name: "RGB to HEX Converter", path: "/rgb-to-hex-converter", category: "Color Tools", description: "Convert RGB color values to HEX." },
  { name: "Color Palette Generator", path: "/color-palette-generator", category: "Color Tools", description: "Generate color palettes." },
  { name: "Contrast Checker", path: "/contrast-checker", category: "Color Tools", description: "Check color contrast for accessibility." },
  { name: "Gradient Generator", path: "/gradient-generator", category: "Color Tools", description: "Create CSS color gradients." },
  { name: "Image Color Extractor", path: "/image-color-extractor", category: "Color Tools", description: "Extract colors from images." },
  { name: "Color Blindness Simulator", path: "/color-blindness-simulator", category: "Color Tools", description: "Simulate color vision deficiencies." },
  { name: "CSS Color Code Generator", path: "/css-color-code-generator", category: "Color Tools", description: "Generate CSS color codes." },
  { name: "Dark/Light Theme Preview", path: "/dark-light-color-preview", category: "Color Tools", description: "Preview colors in dark and light themes." },
  
  { name: "JSON Formatter & Beautifier", path: "/json-formatter", category: "Developer Tools", description: "Format, validate, and beautify JSON data." },
  { name: "JSON to XML Converter", path: "/json-to-xml", category: "Developer Tools", description: "Convert JSON data to XML format." },
  { name: "XML to JSON Converter", path: "/xml-to-json", category: "Developer Tools", description: "Convert XML data to JSON format." },
  { name: "Base64 Encode & Decode", path: "/base64-converter", category: "Developer Tools", description: "Encode to or decode from Base64." },
  { name: "URL Encode & Decode", path: "/url-encoder-decoder", category: "Developer Tools", description: "Encode or decode URLs and URL components." },
  { name: "HTML Minifier & Beautifier", path: "/html-minifier-beautifier", category: "Developer Tools", description: "Minify or beautify HTML code." },
  { name: "CSS Minifier & Beautifier", path: "/css-minifier-beautifier", category: "Developer Tools", description: "Minify or beautify CSS code." },
  { name: "JavaScript Minifier & Beautifier", path: "/javascript-minifier-beautifier", category: "Developer Tools", description: "Minify or beautify JavaScript code." },
  { name: "UUID Generator", path: "/uuid-generator", category: "Developer Tools", description: "Generate universally unique identifiers (UUIDs/GUIDs)." },
  { name: "Lorem Ipsum Generator", path: "/lorem-ipsum-generator", category: "Developer Tools", description: "Generate Lorem Ipsum placeholder text." },
  { name: "Color Code Converter (HEX, RGB, HSL)", path: "/color-code-converter", category: "Developer Tools", description: "Convert between HEX, RGB, and HSL color codes." },
  { name: "Regex Tester", path: "/regex-tester", category: "Developer Tools", description: "Test and validate regular expressions with highlighting." },
  { name: "HTML Entity Encoder/Decoder", path: "/html-entity-converter", category: "Developer Tools", description: "Encode or decode HTML entities." },
  { name: "Timestamp Converter (Dev)", path: "/timestamp-converter", category: "Developer Tools", description: "Convert Unix timestamps to human-readable dates and vice-versa." },
  { name: "Character Counter with Byte Info", path: "/character-byte-counter", category: "Developer Tools", description: "Count characters, words, lines, and view byte size." },
  { name: "HTTP Headers Viewer", path: "/http-headers-viewer", category: "Developer Tools", description: "View your browser's current HTTP request headers. (Client-Side)" },

  { name: "Password Generator", path: "/password-generator", category: "Security Tools", description: "Generate strong, secure, and random passwords." },
  { name: "Password Strength Checker", path: "/password-strength-checker", category: "Security Tools", description: "Check how strong your password is and get security tips." },
  { name: "MD5 Hash Generator", path: "/md5-generator", category: "Security Tools", description: "Create MD5 hashes from text." },
  { name: "SHA256 Hash Generator", path: "/sha256-generator", category: "Security Tools", description: "Generate SHA256 hashes with high-level encryption." },
  { name: "Text Encryption/Decryption", path: "/secure-text-encrypt-decrypt", category: "Security Tools", description: "Encrypt or decrypt messages using a passphrase." },
  { name: "Random PIN Generator", path: "/random-pin-generator", category: "Security Tools", description: "Instantly create secure numeric PINs." },

  { name: "Random Number Generator", path: "/random-number-generator", category: "Miscellaneous Tools", description: "Generate random numbers within a specified range." },
  { name: "Joke Generator", path: "/joke-generator", category: "Miscellaneous Tools", description: "Get a random joke to brighten your day." },
  { name: "Would You Rather Generator", path: "/would-you-rather-generator", category: "Miscellaneous Tools", description: "Get fun 'Would You Rather' questions." },
  { name: "Truth or Dare Generator", path: "/truth-or-dare-generator", category: "Miscellaneous Tools", description: "Generate Truth or Dare questions." },
  { name: "Magic 8 Ball", path: "/magic-8-ball", category: "Miscellaneous Tools", description: "Ask the Magic 8 Ball a yes/no question." },
  { name: "Nickname Generator", path: "/nickname-generator", category: "Miscellaneous Tools", description: "Generate cool and fun nicknames." },
  { name: "Age Calculator (Misc)", path: "/misc-age-calculator", category: "Miscellaneous Tools", description: "Quickly calculate age from birth date." },
  { name: "Countdown Timer (Misc)", path: "/countdown-timer", category: "Miscellaneous Tools", description: "Set a timer for any event or task." },
  { name: "Fortune Cookie Generator", path: "/fortune-cookie-generator", category: "Miscellaneous Tools", description: "Open a virtual fortune cookie." },
  { name: "Dice Roller", path: "/dice-roller", category: "Miscellaneous Tools", description: "Roll one or more virtual dice." },
  { name: "Birthday Countdown", path: "/birthday-countdown", category: "Miscellaneous Tools", description: "Count down to your next birthday." },
  { name: "Quote of the Day", path: "/quote-of-the-day", category: "Miscellaneous Tools", description: "Get an inspiring quote daily." },
  { name: "Fun Fact Generator", path: "/fun-fact-generator", category: "Miscellaneous Tools", description: "Discover interesting and fun facts." },
  { name: "Emoji Translator", path: "/emoji-translator", category: "Miscellaneous Tools", description: "Translate text to emojis and vice-versa (simple version)." },
  { name: "Coin Flip Simulator", path: "/coin-flip-simulator", category: "Miscellaneous Tools", description: "Flip a virtual coin: Heads or Tails?" },
  { name: "Rock Paper Scissors Game", path: "/rock-paper-scissors", category: "Miscellaneous Tools", description: "Play the classic game of Rock Paper Scissors." },

  { name: "Periodic Table Explorer", path: "/periodic-table-explorer", category: "Science Tools", description: "Interactive periodic table with atomic details." },
  { name: "Molar Mass Calculator", path: "/molar-mass-calculator", category: "Science Tools", description: "Calculate molecular weights from chemical formulas." },
  { name: "DNA Sequence Analyzer", path: "/dna-sequence-analyzer", category: "Science Tools", description: "Analyze and convert DNA sequences." },
  { name: "pH Calculator", path: "/ph-calculator", category: "Science Tools", description: "Calculate pH values from hydrogen ion concentration." },
  { name: "Physics Formula Calculator", path: "/physics-formula-calculator", category: "Science Tools", description: "Solve motion, force, energy formulas." },
  { name: "Planet Weight Calculator", path: "/planet-weight-calculator", category: "Science Tools", description: "Find your weight on other planets." },
  { name: "Astronomical Unit Converter", path: "/astronomical-unit-converter", category: "Science Tools", description: "Convert light-years, AU, parsecs, etc." },
  { name: "Density Calculator", path: "/density-calculator", category: "Science Tools", description: "Calculate mass, volume, or density." },
  { name: "Calorimetry Calculator", path: "/calorimetry-calculator", category: "Science Tools", description: "Find heat transfer values." },
  { name: "Human Body Temperature Converter", path: "/body-temperature-converter", category: "Science Tools", description: "Convert Fahrenheit ↔ Celsius for medical use." },

  { name: "Meta Tag Analyzer", path: "/meta-tag-analyzer", category: "Marketing Tools", description: "Analyze and preview meta tags (paste HTML)." },
  { name: "UTM Link Generator", path: "/utm-link-generator", category: "Marketing Tools", description: "Create UTM tracking links for campaigns." },
  { name: "Keyword Density Checker", path: "/keyword-density-checker", category: "Marketing Tools", description: "Analyze keyword usage in content." },
  { name: "Email Subject Line Tester", path: "/email-subject-line-tester", category: "Marketing Tools", description: "Check effectiveness of email subject lines." },
  { name: "Slogan Generator", path: "/slogan-generator", category: "Marketing Tools", description: "Generate catchy slogans for any brand." },
  { name: "ROI Calculator", path: "/roi-calculator", category: "Marketing Tools", description: "Calculate Return on Investment for campaigns." },
  { name: "Content Idea Generator", path: "/content-idea-generator", category: "Marketing Tools", description: "Generate blog/video content ideas." },
  { name: "Ad Image Size Checker", path: "/ad-image-size-checker", category: "Marketing Tools", description: "Validate ad banner sizes for different platforms." },
  { name: "Competitor Keyword Extractor", path: "/competitor-keyword-extractor", category: "Marketing Tools", description: "Extract keywords from website content (paste text)." },
  { name: "Headline Analyzer", path: "/headline-analyzer", category: "Marketing Tools", description: "Check clickability and readability of titles/headlines." },
  { name: "Meta Tag Generator", path: "/meta-tag-generator", category: "Marketing Tools", description: "Generate SEO meta tags for websites." },
  { name: "Blog Title Generator", path: "/blog-title-generator", category: "Marketing Tools", description: "Generate catchy blog titles." },
  { name: "Ad Copy Generator", path: "/ad-copy-generator", category: "Marketing Tools", description: "Create compelling marketing ad copy." },
  { name: "Ad Character Counter", path: "/ad-character-counter", category: "Marketing Tools", description: "Ensure ad copy meets character limits." },


  { name: "Instagram Bio Generator", path: "/instagram-bio-generator", category: "Social Media Tools", description: "Create stylish and effective Instagram bios." },
  { name: "Hashtag Generator", path: "/hashtag-generator", category: "Social Media Tools", description: "Generate relevant hashtags based on keywords." },
  { name: "Social Media Image Resizer", path: "/social-media-image-resizer", category: "Social Media Tools", description: "Resize images for various social platforms." },
  { name: "Post Scheduler Planner", path: "/post-scheduler-planner", category: "Social Media Tools", description: "Visually plan your social media posts (frontend only)." },
  { name: "Tweet Generator", path: "/tweet-generator", category: "Social Media Tools", description: "Generate tweet ideas within character limits." },
  { name: "YouTube Tag Extractor", path: "/youtube-tag-extractor", category: "Social Media Tools", description: "Extract tags from YouTube video information (paste text)." },
  { name: "Caption Generator", path: "/caption-generator", category: "Social Media Tools", description: "Generate engaging captions for your posts." },
  { name: "Profile Picture Cropper", path: "/profile-picture-cropper", category: "Social Media Tools", description: "Crop images perfectly for social profiles." },
  { name: "Social Media Character Counter", path: "/social-media-character-counter", category: "Social Media Tools", description: "Count characters/words for social media limits." },
  { name: "Emoji Picker & Inserter", path: "/emoji-picker", category: "Social Media Tools", description: "Easily find and copy emojis for your posts." },

  { name: "File Compressor", path: "/file-compressor", category: "File Tools", description: "Compress files into ZIP format client-side." },
  { name: "File Merger (Text/PDF)", path: "/file-merger", category: "File Tools", description: "Merge multiple text or PDF files in-browser." },
  { name: "File Splitter", path: "/file-splitter", category: "File Tools", description: "Split files into smaller parts (text files)." },
  { name: "Rename Multiple Files Tool", path: "/rename-multiple-files", category: "File Tools", description: "Batch rename files using patterns (download renamed)." },
  { name: "File Converter (TXT to CSV)", path: "/txt-csv-converter", category: "File Tools", description: "Convert text files between TXT and CSV formats." },
  { name: "Encrypt/Decrypt File Tool", path: "/encrypt-decrypt-file", category: "File Tools", description: "Basic client-side file encryption/decryption." },
  { name: "Text File Viewer", path: "/text-file-viewer", category: "File Tools", description: "View and read .txt files directly in your browser." },
  { name: "File Size Calculator", path: "/file-size-calculator", category: "File Tools", description: "Calculate file sizes in KB/MB/GB." },
  
  { name: "BMI Calculator (Health)", path: "/health-bmi-calculator", category: "Health & Fitness Tools", description: "Calculate your Body Mass Index for health assessment." },
  { name: "Calorie Needs Calculator", path: "/calorie-needs-calculator", category: "Health & Fitness Tools", description: "Estimate your daily calorie requirements." },
  { name: "Manual Heart Rate Checker", path: "/manual-heart-rate-checker", category: "Health & Fitness Tools", description: "Check your pulse manually with a timer." },
  { name: "Ideal Weight Calculator", path: "/ideal-weight-calculator", category: "Health & Fitness Tools", description: "Calculate your ideal body weight range." },
  { name: "Water Intake Calculator", path: "/water-intake-calculator", category: "Health & Fitness Tools", description: "Estimate your daily water intake needs." },
  { name: "Steps to Calories Converter", path: "/steps-to-calories-converter", category: "Health & Fitness Tools", description: "Convert your steps walked into calories burned." },
  { name: "Sleep Time Calculator", path: "/sleep-time-calculator", category: "Health & Fitness Tools", description: "Find the best times to sleep and wake up." },
  { name: "BMR Calculator", path: "/bmr-calculator", category: "Health & Fitness Tools", description: "Calculate your Basal Metabolic Rate." },

  { name: "Stopwatch", path: "/stopwatch", category: "Calendar & Time Tools", description: "Start, stop, and reset a timer in your browser." },
  { name: "Countdown Timer (Date/Time)", path: "/date-time-countdown-timer", category: "Calendar & Time Tools", description: "Countdown to any specific date and time." },
  { name: "Calendar Generator", path: "/calendar-generator", category: "Calendar & Time Tools", description: "Create and view monthly or yearly calendars." },
  { name: "World Clock", path: "/world-clock", category: "Calendar & Time Tools", description: "Show live time from multiple time zones." },
  { name: "Date Calculator", path: "/date-calculator", category: "Calendar & Time Tools", description: "Calculate the duration (days, etc.) between two dates." },
  { name: "Time Zone Converter", path: "/time-zone-converter", category: "Calendar & Time Tools", description: "Convert time from one zone to another." },
  { name: "Age Calculator (Date/Time)", path: "/date-time-age-calculator", category: "Calendar & Time Tools", description: "Calculate age based on birthdate accurately." },
  { name: "Reminder Tool (Local)", path: "/local-reminder-tool", category: "Calendar & Time Tools", description: "Set local browser notifications/reminders." },

  { name: "EMI Calculator", path: "/emi-calculator", category: "Finance Tools", description: "Calculate Equated Monthly Installment for loans." },
  { name: "Loan Interest Calculator", path: "/loan-interest-calculator", category: "Finance Tools", description: "Estimate total interest paid over loan term." },
  { name: "Credit Card Payoff Calculator", path: "/credit-card-payoff-calculator", category: "Finance Tools", description: "Calculate time to repay credit card debt." },
  { name: "Finance Simple Interest Calculator", path: "/finance-simple-interest-calculator", category: "Finance Tools", description: "Calculate simple interest on loans/savings." },
  { name: "Finance Compound Interest Calculator", path: "/finance-compound-interest-calculator", category: "Finance Tools", description: "Calculate compound interest for investments." },
  { name: "GST Calculator", path: "/gst-calculator", category: "Finance Tools", description: "Add or remove GST from an amount." },
  { name: "SIP Calculator", path: "/sip-calculator", category: "Finance Tools", description: "Estimate mutual fund SIP returns." },
  { name: "Static Currency Converter", path: "/static-currency-converter", category: "Finance Tools", description: "Convert currencies with static rates." },

  { name: "Latitude & Longitude Finder", path: "/lat-long-finder", category: "Geography Tools", description: "Find geographic coordinates of any location." },
  { name: "Geography Time Zone Converter", path: "/geo-timezone-converter", category: "Geography Tools", description: "Convert time between global time zones." },
  { name: "Country Information Finder", path: "/country-info-finder", category: "Geography Tools", description: "Get key facts about any country." },
  { name: "IP Geolocation Tool", path: "/ip-geolocation", category: "Geography Tools", description: "Find geographic location of an IP address." },
  { name: "Geographic Distance Calculator", path: "/distance-calculator", category: "Geography Tools", description: "Calculate distance between two points." },
  { name: "Geography World Clock", path: "/geo-world-clock", category: "Geography Tools", description: "View current times in major world cities." },
  { name: "Currency Info by Country", path: "/country-currency-info", category: "Geography Tools", description: "Find currency details for each country." },
  { name: "Country Flags Viewer", path: "/country-flags-viewer", category: "Geography Tools", description: "View flags of all countries." },

  { name: "AI Text Summarizer", path: "/ai-text-summarizer", category: "AI Tools", description: "Condense long texts into brief summaries." },
  { name: "AI Paraphraser", path: "/ai-paraphraser", category: "AI Tools", description: "Rephrase sentences or paragraphs effectively." },
  { name: "AI Sentiment Analyzer", path: "/ai-sentiment-analyzer", category: "AI Tools", description: "Analyze the emotional tone of text." },
  { name: "AI Grammar Checker", path: "/ai-grammar-checker", category: "AI Tools", description: "Check and correct grammatical errors." },
  { name: "AI Resume Analyzer", path: "/ai-resume-analyzer", category: "AI Tools", description: "Get insights and suggestions for your resume." },
  { name: "AI Image Caption Generator", path: "/ai-image-caption-generator", category: "AI Tools", description: "Generate descriptive captions for images (experimental)." },
  { name: "AI Keyword Extractor", path: "/ai-keyword-extractor", category: "AI Tools", description: "Extract key terms and topics from text." },
  { name: "AI Code Explainer", path: "/ai-code-explainer", category: "AI Tools", description: "Get simple explanations for code snippets." },
  { name: "AI Image Enhancer", path: "/ai-image-enhancer", category: "AI Tools", description: "Enhance images with AI-powered tools and filters." },
  { name: "AI Face Swap", path: "/ai-face-swap", category: "AI Tools", description: "Swap faces between two images with AI-powered processing." },

  { name: "Simple Text Translator", path: "/simple-text-translator", category: "Language Tools", description: "Basic translation for common phrases (e.g., EN-ES)." },
  { name: "Language Detector", path: "/language-detector", category: "Language Tools", description: "Identify the language of a given text." },
  { name: "Morse Code Converter", path: "/morse-code-converter", category: "Language Tools", description: "Convert text to Morse code and vice-versa." },
  { name: "Upside Down Text Generator", path: "/upside-down-text-generator", category: "Language Tools", description: "Flip your text upside down for fun." },
  { name: "Zalgo Text Generator", path: "/zalgo-text-generator", category: "Language Tools", description: "Create 'creepy' or 'glitchy' Zalgo text." },
  { name: "Braille Translator", path: "/braille-translator", category: "Language Tools", description: "Convert text to visual Braille representation." },

  { name: "Random Dice Roller", path: "/game-dice-roller", category: "Game Tools", description: "Roll virtual dice for games." },
  { name: "Playing Card Picker", path: "/playing-card-picker", category: "Game Tools", description: "Draw a random playing card." },
  { name: "Memory Test Game", path: "/memory-test-game", category: "Game Tools", description: "Test your memory with this card matching game." },
  { name: "Reaction Time Tester", path: "/reaction-time-tester", category: "Game Tools", description: "Measure your reaction speed." },
  { name: "Click Speed Tester (CPS)", path: "/click-speed-tester", category: "Game Tools", description: "Test your clicks per second." },
  { name: "Scoreboard Tool", path: "/scoreboard-tool", category: "Game Tools", description: "Keep track of scores for games." },
  { name: "Coin Toss Simulator (Game)", path: "/game-coin-toss", category: "Game Tools", description: "Flip a virtual coin for decisions." },
  { name: "Sudoku Generator & Solver", path: "/sudoku-generator", category: "Game Tools", description: "Generate and play Sudoku puzzles." },
  { name: "Spinner Wheel", path: "/spinner-wheel", category: "Game Tools", description: "Customizable spinner for random choices." },
  { name: "Name Picker Game", path: "/name-picker-game", category: "Game Tools", description: "Randomly pick a name from a list." },
  
  { name: "What Is My IP?", path: "/what-is-my-ip", category: "System Tools", description: "View your public IP address and other network info." },
  { name: "Screen Resolution Checker", path: "/screen-resolution-checker", category: "System Tools", description: "Check your screen resolution and viewport size." },
  { name: "Browser Information Viewer", path: "/browser-info-viewer", category: "System Tools", description: "View detailed information about your browser." },
  { name: "Keyboard Event Tester", path: "/keyboard-tester", category: "System Tools", description: "Test your keyboard keys and view event codes." },
  { name: "Mouse Position Tracker", path: "/mouse-position-tracker", category: "System Tools", description: "Track the X/Y coordinates of your mouse pointer." },
  { name: "Internet Speed Simulator", path: "/internet-speed-simulator", category: "System Tools", description: "Simulate an internet speed test (visual only)." },
  { name: "Ping Test Tool", path: "/ping-generator", category: "System Tools", description: "Check network latency to servers (visual only)." },
  { name: "Battery Status Checker", path: "/battery-status-checker", category: "System Tools", description: "View your device's battery level and status." },
  { name: "Device Orientation Tester", path: "/device-orientation-tester", category: "System Tools", description: "Test device orientation sensors (alpha, beta, gamma)." },
  { name: "Online/Offline Status Checker", path: "/online-offline-status-checker", category: "System Tools", description: "Check your browser's current online/offline status." }
];

export const allToolsSearchable = individualTools.map(tool => ({
  ...tool,
  ...allToolCategories.find(category => category.name === tool.category)
}));